# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_create_project', models.BooleanField(default=False, help_text='Si se marca esta casilla, no ser\xe1 necesario crear los proyectos en el admin, se auto crear\xe1n dependiendo de los datos que vayan llegando')),
                ('slack_token', models.CharField(max_length=200, verbose_name='Slack token')),
                ('slack_notify', models.BooleanField(default=True)),
            ],
        ),
    ]
