# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 06:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_console', models.CharField(max_length=100, verbose_name='Console log type')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_error', models.TextField(blank=True, null=True, verbose_name='File')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('issues', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_name', models.CharField(default='window', max_length=100, verbose_name='Error type')),
                ('line', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('foozle_version', models.CharField(max_length=100, verbose_name='Foozle version')),
                ('meta_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('consoles', models.ManyToManyField(to='errors.ConsoleError')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedOn', models.DateTimeField()),
                ('completedOn', models.DateTimeField()),
                ('url', models.TextField()),
                ('method', models.CharField(max_length=100, verbose_name='Method')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='errordetail',
            name='networks',
            field=models.ManyToManyField(to='errors.Network'),
        ),
        migrations.AddField(
            model_name='error',
            name='errors',
            field=models.ManyToManyField(to='errors.ErrorDetail'),
        ),
    ]
