# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='actions',
        ),
        migrations.AddField(
            model_name='action',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Page'),
        ),
    ]
