# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180915_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navigation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project'),
        ),
    ]
