# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180916_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='availabilities',
            field=models.ManyToManyField(blank=True, to='data.Availability'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='data.Booking'),
        ),
    ]
